### ISSUE TITLE
Merge 후 버그 수정

### ISSUE THREAD

**Issue by thejae-u** [hwi-middle/2024-CKGraduationWork#139]
- Merge 과정에서 발생한 오류에 대해서 수정합니다.

**Comment by hwi-middle** [comment]
main에 force push할 수 있는 권한을 드렸습니다. reset하고 다시 merge해서 force push하는게 가장 편할 것 같습니다.

**Comment by thejae-u** [comment]
확인했습니다

**Comment by thejae-u** [comment]
이슈는 Close 처리하겠습니다
