### ISSUE TITLE
암살 연타 시 NullReferenceException 에러

### ISSUE THREAD

**Issue by HonBack12** [hwi-middle/2024-CKGraduationWork#33]
![image](https://github.com/hwi-middle/2024-CKGraduationWork/assets/74600293/83fc7eb3-03f4-45e0-a6d1-7d5c15a4ea08)
적 암살 시 암살 버튼 연타했을 때 해당 버그가 발생합니다.

**Comment by hwi-middle** [comment]
암살 시스템 전반이 수정될 예정이므로 close 합니다.
