### ISSUE TITLE
벽 뒤로 와이어 포인트 UI가 표시되는 문제

### ISSUE THREAD

**Issue by HonBack12** [hwi-middle/2024-CKGraduationWork#36]
![image](https://github.com/hwi-middle/2024-CKGraduationWork/assets/74600293/e2aca8de-f503-4808-a9e3-e03fc57069a0)
와이어 포인트 UI가 벽 뒤에 있어도 출력되는 문제를 발견했습니다.

**Comment by thejae-u** [comment]
[버그가 수정 된 브랜치](https://github.com/hwi-middle/2024-CKGraduationWork/tree/31-ImplPcSystem)

해당하는 브랜치에서 버그 수정하였습니다.
![wireUI](https://github.com/hwi-middle/2024-CKGraduationWork/assets/31125543/a6c8eb9b-68c8-4c53-aca1-b978e2e5a5e9)

**Comment by hwi-middle** [comment]
@thejae-u 해당 브랜치 PR 넣을 때 이 issue도 resolved로 mark해주세용
